--- !gmacc.config.NeuralNetwork
filecore: 'data'
indir: 'example_data/MT/1_pgd/'
outdir: 'example_data/MT/1_pgd/nn/'
# outdir: 'example_data/RS/1_pgd/'
# outdir: 'example_data/RS/1_pgd/nn/'
maxepochnum: 100
minepochnum: 1
validepochnum: 10
device: 'cpu'
targetmode: 'multi'
dropouts: [0]
activations: ['elu']
optimizers: ['adam']
learningtypes: ['default']
batchsizes: [0.1]
hiddenlayers: [[10, 10], ['5n','5n']]
