--- !gmacc.config.NeuralNetwork
config_path: ''
filecore: 'data'
indir: '../02_synthetic_database_and_nn_creation/example_data/MT/1_pgd/'
outdir: '../02_synthetic_database_and_nn_creation/example_data/MT/1_pgd/nn/cpu_elu_adam_800_default_mse_0.0_[10,10]-multi'
modeldir: '../02_synthetic_database_and_nn_creation/example_data/MT/1_pgd/nn/cpu_elu_adam_800_default_mse_0.0_[10,10]-multi'